/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface LeaderboardEntry {
  'userName' : string,
  'totalCO2Grams' : number,
  'tripCount' : bigint,
}
export type Time = bigint;
export type TransportMode = { 'bus' : null } |
  { 'car' : null } |
  { 'train' : null } |
  { 'bicycle' : null } |
  { 'walk' : null } |
  { 'plane' : null };
export interface Trip {
  'userName' : string,
  'co2Grams' : number,
  'distanceKm' : number,
  'timestamp' : Time,
  'transportMode' : TransportMode,
}
export interface TripInput {
  'userName' : string,
  'co2Grams' : number,
  'distanceKm' : number,
  'transportMode' : TransportMode,
}
export interface TripSummary {
  'totalCO2' : number,
  'entries' : Array<Trip>,
  'totalDistance' : number,
}
export interface _SERVICE {
  'addTrip' : ActorMethod<[TripInput], undefined>,
  'calculateTotalDistance' : ActorMethod<[], number>,
  'deleteTrip' : ActorMethod<[string], undefined>,
  'getAllTrips' : ActorMethod<[], Array<Trip>>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getTotalCO2Emitted' : ActorMethod<[], number>,
  'getTotalTrips' : ActorMethod<[], bigint>,
  'getTripById' : ActorMethod<[string], Trip>,
  'getTripSummaryByUserName' : ActorMethod<[string], TripSummary>,
  'getTripsByUserName' : ActorMethod<[string], Array<Trip>>,
  'updateTrip' : ActorMethod<[string, TripInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];