/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TransportMode = IDL.Variant({
  'bus' : IDL.Null,
  'car' : IDL.Null,
  'train' : IDL.Null,
  'bicycle' : IDL.Null,
  'walk' : IDL.Null,
  'plane' : IDL.Null,
});
export const TripInput = IDL.Record({
  'userName' : IDL.Text,
  'co2Grams' : IDL.Float64,
  'distanceKm' : IDL.Float64,
  'transportMode' : TransportMode,
});
export const Time = IDL.Int;
export const Trip = IDL.Record({
  'userName' : IDL.Text,
  'co2Grams' : IDL.Float64,
  'distanceKm' : IDL.Float64,
  'timestamp' : Time,
  'transportMode' : TransportMode,
});
export const LeaderboardEntry = IDL.Record({
  'userName' : IDL.Text,
  'totalCO2Grams' : IDL.Float64,
  'tripCount' : IDL.Nat,
});
export const TripSummary = IDL.Record({
  'totalCO2' : IDL.Float64,
  'entries' : IDL.Vec(Trip),
  'totalDistance' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addTrip' : IDL.Func([TripInput], [], []),
  'calculateTotalDistance' : IDL.Func([], [IDL.Float64], ['query']),
  'deleteTrip' : IDL.Func([IDL.Text], [], []),
  'getAllTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getTotalCO2Emitted' : IDL.Func([], [IDL.Float64], ['query']),
  'getTotalTrips' : IDL.Func([], [IDL.Nat], ['query']),
  'getTripById' : IDL.Func([IDL.Text], [Trip], ['query']),
  'getTripSummaryByUserName' : IDL.Func([IDL.Text], [TripSummary], ['query']),
  'getTripsByUserName' : IDL.Func([IDL.Text], [IDL.Vec(Trip)], ['query']),
  'updateTrip' : IDL.Func([IDL.Text, TripInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TransportMode = IDL.Variant({
    'bus' : IDL.Null,
    'car' : IDL.Null,
    'train' : IDL.Null,
    'bicycle' : IDL.Null,
    'walk' : IDL.Null,
    'plane' : IDL.Null,
  });
  const TripInput = IDL.Record({
    'userName' : IDL.Text,
    'co2Grams' : IDL.Float64,
    'distanceKm' : IDL.Float64,
    'transportMode' : TransportMode,
  });
  const Time = IDL.Int;
  const Trip = IDL.Record({
    'userName' : IDL.Text,
    'co2Grams' : IDL.Float64,
    'distanceKm' : IDL.Float64,
    'timestamp' : Time,
    'transportMode' : TransportMode,
  });
  const LeaderboardEntry = IDL.Record({
    'userName' : IDL.Text,
    'totalCO2Grams' : IDL.Float64,
    'tripCount' : IDL.Nat,
  });
  const TripSummary = IDL.Record({
    'totalCO2' : IDL.Float64,
    'entries' : IDL.Vec(Trip),
    'totalDistance' : IDL.Float64,
  });
  
  return IDL.Service({
    'addTrip' : IDL.Func([TripInput], [], []),
    'calculateTotalDistance' : IDL.Func([], [IDL.Float64], ['query']),
    'deleteTrip' : IDL.Func([IDL.Text], [], []),
    'getAllTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getTotalCO2Emitted' : IDL.Func([], [IDL.Float64], ['query']),
    'getTotalTrips' : IDL.Func([], [IDL.Nat], ['query']),
    'getTripById' : IDL.Func([IDL.Text], [Trip], ['query']),
    'getTripSummaryByUserName' : IDL.Func([IDL.Text], [TripSummary], ['query']),
    'getTripsByUserName' : IDL.Func([IDL.Text], [IDL.Vec(Trip)], ['query']),
    'updateTrip' : IDL.Func([IDL.Text, TripInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };