/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LeaderboardEntry {
    userName: string;
    totalCO2Grams: number;
    tripCount: bigint;
}
export interface TripSummary {
    totalCO2: number;
    entries: Array<Trip>;
    totalDistance: number;
}
export interface Trip {
    userName: string;
    co2Grams: number;
    distanceKm: number;
    timestamp: Time;
    transportMode: TransportMode;
}
export interface TripInput {
    userName: string;
    co2Grams: number;
    distanceKm: number;
    transportMode: TransportMode;
}
export type Time = bigint;
export enum TransportMode {
    bus = "bus",
    car = "car",
    train = "train",
    bicycle = "bicycle",
    walk = "walk",
    plane = "plane"
}
export interface backendInterface {
    addTrip(tripInput: TripInput): Promise<void>;
    calculateTotalDistance(): Promise<number>;
    deleteTrip(id: string): Promise<void>;
    getAllTrips(): Promise<Array<Trip>>;
    getLeaderboard(): Promise<Array<LeaderboardEntry>>;
    getTotalCO2Emitted(): Promise<number>;
    getTotalTrips(): Promise<bigint>;
    getTripById(id: string): Promise<Trip>;
    getTripSummaryByUserName(userName: string): Promise<TripSummary>;
    getTripsByUserName(userName: string): Promise<Array<Trip>>;
    updateTrip(id: string, tripInput: TripInput): Promise<void>;
}
import type { Time as _Time, TransportMode as _TransportMode, Trip as _Trip, TripInput as _TripInput, TripSummary as _TripSummary } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addTrip(arg0: TripInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTrip(to_candid_TripInput_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTrip(to_candid_TripInput_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async calculateTotalDistance(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateTotalDistance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateTotalDistance();
            return result;
        }
    }
    async deleteTrip(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTrip(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTrip(arg0);
            return result;
        }
    }
    async getAllTrips(): Promise<Array<Trip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTrips();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTrips();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaderboard(): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return result;
        }
    }
    async getTotalCO2Emitted(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalCO2Emitted();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalCO2Emitted();
            return result;
        }
    }
    async getTotalTrips(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalTrips();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalTrips();
            return result;
        }
    }
    async getTripById(arg0: string): Promise<Trip> {
        if (this.processError) {
            try {
                const result = await this.actor.getTripById(arg0);
                return from_candid_Trip_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTripById(arg0);
            return from_candid_Trip_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTripSummaryByUserName(arg0: string): Promise<TripSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getTripSummaryByUserName(arg0);
                return from_candid_TripSummary_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTripSummaryByUserName(arg0);
            return from_candid_TripSummary_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTripsByUserName(arg0: string): Promise<Array<Trip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTripsByUserName(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTripsByUserName(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTrip(arg0: string, arg1: TripInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTrip(arg0, to_candid_TripInput_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTrip(arg0, to_candid_TripInput_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_TransportMode_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransportMode): TransportMode {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_TripSummary_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TripSummary): TripSummary {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Trip_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Trip): Trip {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalCO2: number;
    entries: Array<_Trip>;
    totalDistance: number;
}): {
    totalCO2: number;
    entries: Array<Trip>;
    totalDistance: number;
} {
    return {
        totalCO2: value.totalCO2,
        entries: from_candid_vec_n5(_uploadFile, _downloadFile, value.entries),
        totalDistance: value.totalDistance
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userName: string;
    co2Grams: number;
    distanceKm: number;
    timestamp: _Time;
    transportMode: _TransportMode;
}): {
    userName: string;
    co2Grams: number;
    distanceKm: number;
    timestamp: Time;
    transportMode: TransportMode;
} {
    return {
        userName: value.userName,
        co2Grams: value.co2Grams,
        distanceKm: value.distanceKm,
        timestamp: value.timestamp,
        transportMode: from_candid_TransportMode_n8(_uploadFile, _downloadFile, value.transportMode)
    };
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bus: null;
} | {
    car: null;
} | {
    train: null;
} | {
    bicycle: null;
} | {
    walk: null;
} | {
    plane: null;
}): TransportMode {
    return "bus" in value ? TransportMode.bus : "car" in value ? TransportMode.car : "train" in value ? TransportMode.train : "bicycle" in value ? TransportMode.bicycle : "walk" in value ? TransportMode.walk : "plane" in value ? TransportMode.plane : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Trip>): Array<Trip> {
    return value.map((x)=>from_candid_Trip_n6(_uploadFile, _downloadFile, x));
}
function to_candid_TransportMode_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransportMode): _TransportMode {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_TripInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TripInput): _TripInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userName: string;
    co2Grams: number;
    distanceKm: number;
    transportMode: TransportMode;
}): {
    userName: string;
    co2Grams: number;
    distanceKm: number;
    transportMode: _TransportMode;
} {
    return {
        userName: value.userName,
        co2Grams: value.co2Grams,
        distanceKm: value.distanceKm,
        transportMode: to_candid_TransportMode_n3(_uploadFile, _downloadFile, value.transportMode)
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransportMode): {
    bus: null;
} | {
    car: null;
} | {
    train: null;
} | {
    bicycle: null;
} | {
    walk: null;
} | {
    plane: null;
} {
    return value == TransportMode.bus ? {
        bus: null
    } : value == TransportMode.car ? {
        car: null
    } : value == TransportMode.train ? {
        train: null
    } : value == TransportMode.bicycle ? {
        bicycle: null
    } : value == TransportMode.walk ? {
        walk: null
    } : value == TransportMode.plane ? {
        plane: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
